/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as contracts from './contracts'
export type { contracts }
export type { MyToken } from './contracts/MyToken'
export type { PiggyBank } from './contracts/PiggyBank'
